CREATE TABLE IF NOT EXISTS MOVIE
(
	movieId IDENTITY PRIMARY KEY,
	name VARCHAR(100),
	rating INTEGER

);

CREATE TABLE IF NOT EXISTS THEATER
(
	theaterId IDENTITY PRIMARY KEY,
	name VARCHAR(50),
	city VARCHAR(50)

-- 	FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID)
);

CREATE TABLE IF NOT EXISTS PRICE
(
	priceId IDENTITY PRIMARY KEY,
	movieId INTEGER NOT NULL,
	theaterId INTEGER NOT NULL,
  price DECIMAL(12, 2) DEFAULT 0,
	FOREIGN KEY (movieId) REFERENCES MOVIE (movieId),
	FOREIGN KEY (theaterId) REFERENCES THEATER (theaterId)
-- 	FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID)
);